### ISSUE TITLE
Add support for blank tile

### ISSUE THREAD

**Issue by gurshabad** [gurshabad/scrabby#7]

**Comment by kshanmol** [comment]
added support.
remaining issues:
1. scoring
2. a bug which causes the blank tile to be overwritten sometimes in the GUI.

**Comment by gurshabad** [comment]
3. Implement a way to get rid of blank tiles in the shuffle mechanism

**Comment by kshanmol** [comment]
In future, add support for playing blank tile as a letter also currently on the rack.
